export interface WordPair {
  civilian: string;
  undercover: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
}

export const WORD_PAIRS: WordPair[] = [
  // Food
  { civilian: "Pizza", undercover: "Calzone", category: "Food", difficulty: "hard" },
  { civilian: "Pizza", undercover: "Burger", category: "Food", difficulty: "medium" },
  { civilian: "Sushi", undercover: "Sashimi", category: "Food", difficulty: "hard" },
  { civilian: "Burger", undercover: "Sandwich", category: "Food", difficulty: "hard" },
  { civilian: "Pasta", undercover: "Noodles", category: "Food", difficulty: "hard" },
  { civilian: "Taco", undercover: "Burrito", category: "Food", difficulty: "hard" },
  { civilian: "Pancake", undercover: "Waffle", category: "Food", difficulty: "hard" },
  { civilian: "Donut", undercover: "Bagel", category: "Food", difficulty: "medium" },
  { civilian: "Ice Cream", undercover: "Gelato", category: "Food", difficulty: "hard" },
  { civilian: "Chocolate", undercover: "Candy", category: "Food", difficulty: "medium" },
  { civilian: "Apple", undercover: "Pear", category: "Food", difficulty: "hard" },
  { civilian: "Banana", undercover: "Plantain", category: "Food", difficulty: "hard" },
  { civilian: "Bread", undercover: "Toast", category: "Food", difficulty: "hard" },
  { civilian: "Soup", undercover: "Stew", category: "Food", difficulty: "hard" },
  { civilian: "Fries", undercover: "Chips", category: "Food", difficulty: "hard" },
  { civilian: "Cupcake", undercover: "Muffin", category: "Food", difficulty: "hard" },
  { civilian: "Cookie", undercover: "Biscuit", category: "Food", difficulty: "hard" },
  { civilian: "Ramen", undercover: "Pho", category: "Food", difficulty: "hard" },
  { civilian: "Croissant", undercover: "Brioche", category: "Food", difficulty: "hard" },
  { civilian: "Lemon", undercover: "Lime", category: "Food", difficulty: "hard" },
  { civilian: "Strawberry", undercover: "Raspberry", category: "Food", difficulty: "hard" },
  { civilian: "Peach", undercover: "Nectarine", category: "Food", difficulty: "hard" },

  // Drinks
  { civilian: "Coffee", undercover: "Espresso", category: "Drinks", difficulty: "hard" },
  { civilian: "Latte", undercover: "Cappuccino", category: "Drinks", difficulty: "hard" },
  { civilian: "Whiskey", undercover: "Bourbon", category: "Drinks", difficulty: "hard" },
  { civilian: "Milk", undercover: "Cream", category: "Drinks", difficulty: "hard" },
  { civilian: "Smoothie", undercover: "Milkshake", category: "Drinks", difficulty: "hard" },
  { civilian: "Cocktail", undercover: "Mocktail", category: "Drinks", difficulty: "hard" },
  { civilian: "Sake", undercover: "Soju", category: "Drinks", difficulty: "hard" },
  { civilian: "Coffee", undercover: "Black Tea", category: "Drinks", difficulty: "medium" },
  { civilian: "Beer", undercover: "Cider", category: "Drinks", difficulty: "medium" },
  { civilian: "Cola", undercover: "Root Beer", category: "Drinks", difficulty: "medium" },
  { civilian: "Wine", undercover: "Champagne", category: "Drinks", difficulty: "medium" },
  { civilian: "Tea", undercover: "Coffee", category: "Drinks", difficulty: "medium" },
  { civilian: "Matcha", undercover: "Green Tea", category: "Drinks", difficulty: "hard" },
  { civilian: "Vodka", undercover: "Gin", category: "Drinks", difficulty: "hard" },
  { civilian: "Tequila", undercover: "Mezcal", category: "Drinks", difficulty: "hard" },
  { civilian: "Lemonade", undercover: "Limeade", category: "Drinks", difficulty: "hard" },

  // Animals
  { civilian: "Lion", undercover: "Tiger", category: "Animals", difficulty: "hard" },
  { civilian: "Crocodile", undercover: "Alligator", category: "Animals", difficulty: "hard" },
  { civilian: "Frog", undercover: "Toad", category: "Animals", difficulty: "hard" },
  { civilian: "Horse", undercover: "Donkey", category: "Animals", difficulty: "hard" },
  { civilian: "Eagle", undercover: "Hawk", category: "Animals", difficulty: "hard" },
  { civilian: "Rabbit", undercover: "Hare", category: "Animals", difficulty: "hard" },
  { civilian: "Bee", undercover: "Wasp", category: "Animals", difficulty: "hard" },
  { civilian: "Penguin", undercover: "Puffin", category: "Animals", difficulty: "hard" },
  { civilian: "Butterfly", undercover: "Moth", category: "Animals", difficulty: "hard" },
  { civilian: "Turtle", undercover: "Tortoise", category: "Animals", difficulty: "hard" },
  { civilian: "Mouse", undercover: "Rat", category: "Animals", difficulty: "hard" },
  { civilian: "Squirrel", undercover: "Chipmunk", category: "Animals", difficulty: "hard" },
  { civilian: "Fox", undercover: "Coyote", category: "Animals", difficulty: "hard" },
  { civilian: "Octopus", undercover: "Squid", category: "Animals", difficulty: "hard" },
  { civilian: "Crab", undercover: "Lobster", category: "Animals", difficulty: "hard" },
  { civilian: "Dog", undercover: "Wolf", category: "Animals", difficulty: "medium" },
  { civilian: "Cat", undercover: "Tiger", category: "Animals", difficulty: "medium" },
  { civilian: "Shark", undercover: "Dolphin", category: "Animals", difficulty: "medium" },
  { civilian: "Bear", undercover: "Panda", category: "Animals", difficulty: "medium" },
  { civilian: "Goat", undercover: "Sheep", category: "Animals", difficulty: "medium" },
  { civilian: "Zebra", undercover: "Horse", category: "Animals", difficulty: "medium" },
  { civilian: "Giraffe", undercover: "Camel", category: "Animals", difficulty: "easy" },
  { civilian: "Whale", undercover: "Shark", category: "Animals", difficulty: "easy" },

  // Places
  { civilian: "Mountain", undercover: "Hill", category: "Places", difficulty: "hard" },
  { civilian: "Forest", undercover: "Jungle", category: "Places", difficulty: "hard" },
  { civilian: "City", undercover: "Town", category: "Places", difficulty: "hard" },
  { civilian: "Library", undercover: "Bookstore", category: "Places", difficulty: "hard" },
  { civilian: "Hospital", undercover: "Clinic", category: "Places", difficulty: "hard" },
  { civilian: "Cinema", undercover: "Theatre", category: "Places", difficulty: "hard" },
  { civilian: "Hotel", undercover: "Motel", category: "Places", difficulty: "hard" },
  { civilian: "Park", undercover: "Garden", category: "Places", difficulty: "hard" },
  { civilian: "Castle", undercover: "Palace", category: "Places", difficulty: "hard" },
  { civilian: "Restaurant", undercover: "Bistro", category: "Places", difficulty: "hard" },
  { civilian: "Bar", undercover: "Pub", category: "Places", difficulty: "hard" },
  { civilian: "Museum", undercover: "Gallery", category: "Places", difficulty: "hard" },
  { civilian: "Stadium", undercover: "Arena", category: "Places", difficulty: "hard" },
  { civilian: "Subway", undercover: "Metro", category: "Places", difficulty: "hard" },
  { civilian: "Harbor", undercover: "Marina", category: "Places", difficulty: "hard" },
  { civilian: "Cabin", undercover: "Chalet", category: "Places", difficulty: "hard" },
  { civilian: "Farm", undercover: "Ranch", category: "Places", difficulty: "hard" },
  { civilian: "Church", undercover: "Cathedral", category: "Places", difficulty: "hard" },
  { civilian: "Beach", undercover: "Lake", category: "Places", difficulty: "medium" },
  { civilian: "Beach", undercover: "Pool", category: "Places", difficulty: "medium" },
  { civilian: "Gym", undercover: "Studio", category: "Places", difficulty: "medium" },
  { civilian: "Airport", undercover: "Train Station", category: "Places", difficulty: "medium" },
  { civilian: "Bakery", undercover: "Cafe", category: "Places", difficulty: "medium" },
  { civilian: "Aquarium", undercover: "Zoo", category: "Places", difficulty: "medium" },
  { civilian: "Island", undercover: "Peninsula", category: "Places", difficulty: "medium" },
  { civilian: "Cave", undercover: "Mine", category: "Places", difficulty: "medium" },
  { civilian: "Desert", undercover: "Beach", category: "Places", difficulty: "easy" },

  // Sports
  { civilian: "Football", undercover: "Rugby", category: "Sports", difficulty: "hard" },
  { civilian: "Tennis", undercover: "Badminton", category: "Sports", difficulty: "hard" },
  { civilian: "Boxing", undercover: "MMA", category: "Sports", difficulty: "hard" },
  { civilian: "Swimming", undercover: "Diving", category: "Sports", difficulty: "hard" },
  { civilian: "Skiing", undercover: "Snowboarding", category: "Sports", difficulty: "hard" },
  { civilian: "Golf", undercover: "Mini Golf", category: "Sports", difficulty: "hard" },
  { civilian: "Hockey", undercover: "Lacrosse", category: "Sports", difficulty: "hard" },
  { civilian: "Soccer", undercover: "Futsal", category: "Sports", difficulty: "hard" },
  { civilian: "Cycling", undercover: "BMX", category: "Sports", difficulty: "hard" },
  { civilian: "Surfing", undercover: "Bodyboarding", category: "Sports", difficulty: "hard" },
  { civilian: "Skateboard", undercover: "Rollerblade", category: "Sports", difficulty: "hard" },
  { civilian: "Fencing", undercover: "Kendo", category: "Sports", difficulty: "hard" },
  { civilian: "Wrestling", undercover: "Judo", category: "Sports", difficulty: "hard" },
  { civilian: "Karate", undercover: "Taekwondo", category: "Sports", difficulty: "hard" },
  { civilian: "Yoga", undercover: "Pilates", category: "Sports", difficulty: "hard" },
  { civilian: "Billiards", undercover: "Snooker", category: "Sports", difficulty: "hard" },
  { civilian: "Rowing", undercover: "Canoeing", category: "Sports", difficulty: "hard" },
  { civilian: "Climbing", undercover: "Bouldering", category: "Sports", difficulty: "hard" },
  { civilian: "Basketball", undercover: "Volleyball", category: "Sports", difficulty: "medium" },
  { civilian: "Cricket", undercover: "Baseball", category: "Sports", difficulty: "medium" },
  { civilian: "Chess", undercover: "Checkers", category: "Sports", difficulty: "medium" },
  { civilian: "Archery", undercover: "Darts", category: "Sports", difficulty: "medium" },
  { civilian: "Bowling", undercover: "Lawn Bowls", category: "Sports", difficulty: "medium" },
  { civilian: "Sailing", undercover: "Windsurfing", category: "Sports", difficulty: "medium" },

  // Tech
  { civilian: "Google", undercover: "Bing", category: "Tech", difficulty: "hard" },
  { civilian: "Netflix", undercover: "Disney+", category: "Tech", difficulty: "hard" },
  { civilian: "Instagram", undercover: "Snapchat", category: "Tech", difficulty: "hard" },
  { civilian: "Twitter", undercover: "Threads", category: "Tech", difficulty: "hard" },
  { civilian: "WhatsApp", undercover: "Telegram", category: "Tech", difficulty: "hard" },
  { civilian: "PlayStation", undercover: "Xbox", category: "Tech", difficulty: "hard" },
  { civilian: "Bitcoin", undercover: "Ethereum", category: "Tech", difficulty: "hard" },
  { civilian: "MacBook", undercover: "Surface", category: "Tech", difficulty: "hard" },
  { civilian: "Chrome", undercover: "Firefox", category: "Tech", difficulty: "hard" },
  { civilian: "Spotify", undercover: "Apple Music", category: "Tech", difficulty: "hard" },
  { civilian: "Twitch", undercover: "Kick", category: "Tech", difficulty: "hard" },
  { civilian: "Zoom", undercover: "Teams", category: "Tech", difficulty: "hard" },
  { civilian: "Uber", undercover: "Lyft", category: "Tech", difficulty: "hard" },
  { civilian: "Airbnb", undercover: "Vrbo", category: "Tech", difficulty: "hard" },
  { civilian: "Steam", undercover: "Epic Games", category: "Tech", difficulty: "hard" },
  { civilian: "Fortnite", undercover: "Apex Legends", category: "Tech", difficulty: "hard" },
  { civilian: "Router", undercover: "Modem", category: "Tech", difficulty: "hard" },
  { civilian: "Headphones", undercover: "Earbuds", category: "Tech", difficulty: "hard" },
  { civilian: "iPhone", undercover: "Android", category: "Tech", difficulty: "medium" },
  { civilian: "YouTube", undercover: "TikTok", category: "Tech", difficulty: "medium" },
  { civilian: "Facebook", undercover: "LinkedIn", category: "Tech", difficulty: "medium" },
  { civilian: "Reddit", undercover: "Quora", category: "Tech", difficulty: "medium" },
  { civilian: "Discord", undercover: "Slack", category: "Tech", difficulty: "medium" },
  { civilian: "Nintendo", undercover: "Sega", category: "Tech", difficulty: "medium" },
  { civilian: "Minecraft", undercover: "Roblox", category: "Tech", difficulty: "medium" },
  { civilian: "Wi-Fi", undercover: "Bluetooth", category: "Tech", difficulty: "medium" },
  { civilian: "Monitor", undercover: "Television", category: "Tech", difficulty: "medium" },

  // Nature
  { civilian: "River", undercover: "Stream", category: "Nature", difficulty: "hard" },
  { civilian: "Ocean", undercover: "Sea", category: "Nature", difficulty: "hard" },
  { civilian: "Tornado", undercover: "Hurricane", category: "Nature", difficulty: "hard" },
  { civilian: "Rose", undercover: "Tulip", category: "Nature", difficulty: "hard" },
  { civilian: "Oak", undercover: "Maple", category: "Nature", difficulty: "hard" },
  { civilian: "Pine", undercover: "Fir", category: "Nature", difficulty: "hard" },
  { civilian: "Sunflower", undercover: "Daisy", category: "Nature", difficulty: "hard" },
  { civilian: "Lily", undercover: "Orchid", category: "Nature", difficulty: "hard" },
  { civilian: "Mushroom", undercover: "Truffle", category: "Nature", difficulty: "hard" },
  { civilian: "Thunder", undercover: "Lightning", category: "Nature", difficulty: "hard" },
  { civilian: "Fog", undercover: "Mist", category: "Nature", difficulty: "hard" },
  { civilian: "Hail", undercover: "Sleet", category: "Nature", difficulty: "hard" },
  { civilian: "Cliff", undercover: "Bluff", category: "Nature", difficulty: "hard" },
  { civilian: "Canyon", undercover: "Valley", category: "Nature", difficulty: "hard" },
  { civilian: "Glacier", undercover: "Iceberg", category: "Nature", difficulty: "hard" },
  { civilian: "Comet", undercover: "Asteroid", category: "Nature", difficulty: "hard" },
  { civilian: "Rain", undercover: "Snow", category: "Nature", difficulty: "medium" },
  { civilian: "Cactus", undercover: "Succulent", category: "Nature", difficulty: "medium" },
  { civilian: "Coral", undercover: "Sponge", category: "Nature", difficulty: "medium" },
  { civilian: "Earthquake", undercover: "Landslide", category: "Nature", difficulty: "medium" },
  { civilian: "Aurora", undercover: "Eclipse", category: "Nature", difficulty: "medium" },
  { civilian: "Sun", undercover: "Moon", category: "Nature", difficulty: "easy" },

  // Objects
  { civilian: "Pen", undercover: "Pencil", category: "Objects", difficulty: "hard" },
  { civilian: "Guitar", undercover: "Ukulele", category: "Objects", difficulty: "hard" },
  { civilian: "Piano", undercover: "Keyboard", category: "Objects", difficulty: "hard" },
  { civilian: "Clock", undercover: "Watch", category: "Objects", difficulty: "hard" },
  { civilian: "Camera", undercover: "Phone Camera", category: "Objects", difficulty: "hard" },
  { civilian: "Chair", undercover: "Stool", category: "Objects", difficulty: "hard" },
  { civilian: "Sofa", undercover: "Couch", category: "Objects", difficulty: "hard" },
  { civilian: "Pillow", undercover: "Cushion", category: "Objects", difficulty: "hard" },
  { civilian: "Blanket", undercover: "Quilt", category: "Objects", difficulty: "hard" },
  { civilian: "Lamp", undercover: "Lantern", category: "Objects", difficulty: "hard" },
  { civilian: "Hammer", undercover: "Mallet", category: "Objects", difficulty: "hard" },
  { civilian: "Scissors", undercover: "Shears", category: "Objects", difficulty: "hard" },
  { civilian: "Mug", undercover: "Cup", category: "Objects", difficulty: "hard" },
  { civilian: "Bowl", undercover: "Plate", category: "Objects", difficulty: "hard" },
  { civilian: "Bottle", undercover: "Flask", category: "Objects", difficulty: "hard" },
  { civilian: "Umbrella", undercover: "Parasol", category: "Objects", difficulty: "hard" },
  { civilian: "Wallet", undercover: "Purse", category: "Objects", difficulty: "hard" },
  { civilian: "Glasses", undercover: "Goggles", category: "Objects", difficulty: "hard" },
  { civilian: "Necklace", undercover: "Pendant", category: "Objects", difficulty: "hard" },
  { civilian: "Trophy", undercover: "Medal", category: "Objects", difficulty: "hard" },
  { civilian: "Telescope", undercover: "Binoculars", category: "Objects", difficulty: "hard" },
  { civilian: "Flute", undercover: "Clarinet", category: "Objects", difficulty: "hard" },
  { civilian: "Violin", undercover: "Cello", category: "Objects", difficulty: "hard" },
  { civilian: "Phone", undercover: "Tablet", category: "Objects", difficulty: "medium" },
  { civilian: "Laptop", undercover: "Desktop", category: "Objects", difficulty: "medium" },
  { civilian: "Book", undercover: "Magazine", category: "Objects", difficulty: "medium" },
  { civilian: "Backpack", undercover: "Suitcase", category: "Objects", difficulty: "medium" },
  { civilian: "Mirror", undercover: "Window", category: "Objects", difficulty: "medium" },
  { civilian: "Bicycle", undercover: "Motorbike", category: "Objects", difficulty: "medium" },
  { civilian: "Bed", undercover: "Mattress", category: "Objects", difficulty: "medium" },
  { civilian: "Door", undercover: "Gate", category: "Objects", difficulty: "medium" },
  { civilian: "Key", undercover: "Lock", category: "Objects", difficulty: "medium" },
  { civilian: "Rope", undercover: "Cable", category: "Objects", difficulty: "medium" },
  { civilian: "Fork", undercover: "Spoon", category: "Objects", difficulty: "medium" },

  // People & Roles
  { civilian: "Teacher", undercover: "Professor", category: "People & Roles", difficulty: "hard" },
  { civilian: "Chef", undercover: "Baker", category: "People & Roles", difficulty: "hard" },
  { civilian: "Author", undercover: "Journalist", category: "People & Roles", difficulty: "hard" },
  { civilian: "Magician", undercover: "Illusionist", category: "People & Roles", difficulty: "hard" },
  { civilian: "Dentist", undercover: "Orthodontist", category: "People & Roles", difficulty: "hard" },
  { civilian: "Surgeon", undercover: "Anesthesiologist", category: "People & Roles", difficulty: "hard" },
  { civilian: "Carpenter", undercover: "Mason", category: "People & Roles", difficulty: "hard" },
  { civilian: "Mechanic", undercover: "Technician", category: "People & Roles", difficulty: "hard" },
  { civilian: "Tattoo Artist", undercover: "Piercer", category: "People & Roles", difficulty: "hard" },
  { civilian: "Barber", undercover: "Hairdresser", category: "People & Roles", difficulty: "hard" },
  { civilian: "Florist", undercover: "Gardener", category: "People & Roles", difficulty: "hard" },
  { civilian: "Photographer", undercover: "Videographer", category: "People & Roles", difficulty: "hard" },
  { civilian: "Painter", undercover: "Illustrator", category: "People & Roles", difficulty: "hard" },
  { civilian: "Sculptor", undercover: "Potter", category: "People & Roles", difficulty: "hard" },
  { civilian: "Dancer", undercover: "Choreographer", category: "People & Roles", difficulty: "hard" },
  { civilian: "Referee", undercover: "Umpire", category: "People & Roles", difficulty: "hard" },
  { civilian: "King", undercover: "Emperor", category: "People & Roles", difficulty: "hard" },
  { civilian: "Prince", undercover: "Duke", category: "People & Roles", difficulty: "hard" },
  { civilian: "Knight", undercover: "Samurai", category: "People & Roles", difficulty: "hard" },
  { civilian: "Pirate", undercover: "Buccaneer", category: "People & Roles", difficulty: "hard" },
  { civilian: "Doctor", undercover: "Nurse", category: "People & Roles", difficulty: "medium" },
  { civilian: "Pilot", undercover: "Flight Attendant", category: "People & Roles", difficulty: "medium" },
  { civilian: "Firefighter", undercover: "Police Officer", category: "People & Roles", difficulty: "medium" },
  { civilian: "Lawyer", undercover: "Judge", category: "People & Roles", difficulty: "medium" },
  { civilian: "Singer", undercover: "Rapper", category: "People & Roles", difficulty: "medium" },
  { civilian: "Actor", undercover: "Comedian", category: "People & Roles", difficulty: "medium" },
  { civilian: "Engineer", undercover: "Architect", category: "People & Roles", difficulty: "medium" },
  { civilian: "Plumber", undercover: "Electrician", category: "People & Roles", difficulty: "medium" },
  { civilian: "Tailor", undercover: "Cobbler", category: "People & Roles", difficulty: "medium" },
  { civilian: "Director", undercover: "Producer", category: "People & Roles", difficulty: "medium" },
  { civilian: "Athlete", undercover: "Coach", category: "People & Roles", difficulty: "medium" },
  { civilian: "Spy", undercover: "Detective", category: "People & Roles", difficulty: "medium" },

  // Movies & TV
  { civilian: "Star Wars", undercover: "Star Trek", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Avengers", undercover: "Justice League", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Spider-Man", undercover: "Daredevil", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Frozen", undercover: "Tangled", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Pokémon", undercover: "Digimon", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Superman", undercover: "Captain America", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Joker", undercover: "Thanos", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Inception", undercover: "Interstellar", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Shrek", undercover: "Monsters Inc", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Toy Story", undercover: "Cars", category: "Movies & TV", difficulty: "hard" },
  { civilian: "The Lion King", undercover: "The Jungle Book", category: "Movies & TV", difficulty: "hard" },
  { civilian: "The Matrix", undercover: "Equilibrium", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Breaking Bad", undercover: "Better Call Saul", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Friends", undercover: "How I Met Your Mother", category: "Movies & TV", difficulty: "hard" },
  { civilian: "The Office", undercover: "Parks and Recreation", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Game of Thrones", undercover: "The Witcher", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Seinfeld", undercover: "Curb Your Enthusiasm", category: "Movies & TV", difficulty: "hard" },
  { civilian: "The Simpsons", undercover: "Family Guy", category: "Movies & TV", difficulty: "hard" },
  { civilian: "Batman", undercover: "Iron Man", category: "Movies & TV", difficulty: "medium" },
  { civilian: "Mario", undercover: "Sonic", category: "Movies & TV", difficulty: "medium" },
  { civilian: "Thor", undercover: "Hulk", category: "Movies & TV", difficulty: "medium" },
  { civilian: "Stranger Things", undercover: "Dark", category: "Movies & TV", difficulty: "medium" },
  { civilian: "Harry Potter", undercover: "Lord of the Rings", category: "Movies & TV", difficulty: "easy" },
  { civilian: "Titanic", undercover: "Avatar", category: "Movies & TV", difficulty: "easy" },

  // Anime
  { civilian: "Naruto", undercover: "Sasuke", category: "Anime", difficulty: "hard" },
  { civilian: "Goku", undercover: "Vegeta", category: "Anime", difficulty: "hard" },
  { civilian: "Luffy", undercover: "Zoro", category: "Anime", difficulty: "hard" },
  { civilian: "Doraemon", undercover: "Nobita", category: "Anime", difficulty: "medium" },
  { civilian: "Pikachu", undercover: "Raichu", category: "Anime", difficulty: "hard" },
  { civilian: "Attack on Titan", undercover: "Tokyo Ghoul", category: "Anime", difficulty: "hard" },
  { civilian: "Demon Slayer", undercover: "Jujutsu Kaisen", category: "Anime", difficulty: "hard" },
  { civilian: "Tanjiro", undercover: "Nezuko", category: "Anime", difficulty: "medium" },
  { civilian: "One Piece", undercover: "Naruto", category: "Anime", difficulty: "medium" },
  { civilian: "Death Note", undercover: "Code Geass", category: "Anime", difficulty: "hard" },
  { civilian: "Light Yagami", undercover: "L", category: "Anime", difficulty: "hard" },
  { civilian: "Shin-chan", undercover: "Doraemon", category: "Anime", difficulty: "medium" },
  { civilian: "Spy x Family", undercover: "Detective Conan", category: "Anime", difficulty: "medium" },
  { civilian: "Gojo", undercover: "Sukuna", category: "Anime", difficulty: "hard" },
  { civilian: "Dragon Ball", undercover: "Naruto", category: "Anime", difficulty: "medium" },
  { civilian: "Deku", undercover: "Bakugo", category: "Anime", difficulty: "hard" },
  { civilian: "Kakashi", undercover: "Jiraiya", category: "Anime", difficulty: "hard" },
  { civilian: "Sailor Moon", undercover: "Cardcaptor Sakura", category: "Anime", difficulty: "hard" },
  { civilian: "Saitama", undercover: "Genos", category: "Anime", difficulty: "medium" },
  { civilian: "Manga", undercover: "Anime", category: "Anime", difficulty: "hard" },
  { civilian: "Cosplay", undercover: "Costume", category: "Anime", difficulty: "hard" },
  { civilian: "Pokeball", undercover: "Great Ball", category: "Anime", difficulty: "hard" },
  { civilian: "Sharingan", undercover: "Byakugan", category: "Anime", difficulty: "hard" },
  { civilian: "Bleach", undercover: "One Piece", category: "Anime", difficulty: "medium" },
  { civilian: "Shizuka", undercover: "Nobita", category: "Anime", difficulty: "medium" },

  // Music Artists
  { civilian: "Taylor Swift", undercover: "Olivia Rodrigo", category: "Music Artists", difficulty: "hard" },
  { civilian: "Ed Sheeran", undercover: "Shawn Mendes", category: "Music Artists", difficulty: "hard" },
  { civilian: "Justin Bieber", undercover: "Zayn Malik", category: "Music Artists", difficulty: "hard" },
  { civilian: "Bruno Mars", undercover: "The Weeknd", category: "Music Artists", difficulty: "hard" },
  { civilian: "BTS", undercover: "Blackpink", category: "Music Artists", difficulty: "medium" },
  { civilian: "Blackpink", undercover: "TWICE", category: "Music Artists", difficulty: "hard" },
  { civilian: "BTS", undercover: "EXO", category: "Music Artists", difficulty: "hard" },
  { civilian: "Siti Nurhaliza", undercover: "Sheila Majid", category: "Music Artists", difficulty: "hard" },
  { civilian: "Jay Chou", undercover: "JJ Lin", category: "Music Artists", difficulty: "hard" },
  { civilian: "Billie Eilish", undercover: "Olivia Rodrigo", category: "Music Artists", difficulty: "hard" },
  { civilian: "Ariana Grande", undercover: "Selena Gomez", category: "Music Artists", difficulty: "hard" },
  { civilian: "Drake", undercover: "Kendrick Lamar", category: "Music Artists", difficulty: "hard" },
  { civilian: "Eminem", undercover: "Snoop Dogg", category: "Music Artists", difficulty: "medium" },
  { civilian: "Coldplay", undercover: "Maroon 5", category: "Music Artists", difficulty: "hard" },
  { civilian: "Adele", undercover: "Sia", category: "Music Artists", difficulty: "hard" },
  { civilian: "Michael Jackson", undercover: "Bruno Mars", category: "Music Artists", difficulty: "medium" },
  { civilian: "Dua Lipa", undercover: "Katy Perry", category: "Music Artists", difficulty: "hard" },
  { civilian: "Charlie Puth", undercover: "Shawn Mendes", category: "Music Artists", difficulty: "hard" },
  { civilian: "Beyonce", undercover: "Rihanna", category: "Music Artists", difficulty: "hard" },
  { civilian: "Post Malone", undercover: "The Weeknd", category: "Music Artists", difficulty: "hard" },
  { civilian: "Lady Gaga", undercover: "Madonna", category: "Music Artists", difficulty: "hard" },
  { civilian: "Harry Styles", undercover: "Zayn Malik", category: "Music Artists", difficulty: "hard" },
  { civilian: "Faizal Tahir", undercover: "Hael Husaini", category: "Music Artists", difficulty: "hard" },
  { civilian: "Alan Walker", undercover: "Marshmello", category: "Music Artists", difficulty: "hard" },
  { civilian: "Shakira", undercover: "Jennifer Lopez", category: "Music Artists", difficulty: "hard" },

  // Superheroes & Villains
  { civilian: "Batman", undercover: "Iron Man", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Superman", undercover: "Captain America", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Spider-Man", undercover: "Deadpool", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Joker", undercover: "Harley Quinn", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Thor", undercover: "Loki", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Hulk", undercover: "Thanos", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Flash", undercover: "Quicksilver", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Wonder Woman", undercover: "Captain Marvel", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Wolverine", undercover: "Deadpool", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Iron Man", undercover: "War Machine", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Robin", undercover: "Nightwing", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Black Panther", undercover: "Batman", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Hawkeye", undercover: "Green Arrow", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Doctor Strange", undercover: "Scarlet Witch", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Magneto", undercover: "Professor X", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Venom", undercover: "Carnage", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Aquaman", undercover: "Namor", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Ant-Man", undercover: "Wasp", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Green Goblin", undercover: "Joker", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Batmobile", undercover: "Batwing", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Avengers", undercover: "Justice League", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Gotham", undercover: "Metropolis", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Captain America Shield", undercover: "Batarang", category: "Superheroes & Villains", difficulty: "medium" },
  { civilian: "Clark Kent", undercover: "Bruce Wayne", category: "Superheroes & Villains", difficulty: "hard" },
  { civilian: "Supergirl", undercover: "Wonder Woman", category: "Superheroes & Villains", difficulty: "hard" },

  // Sci-Fi & Fantasy
  { civilian: "Harry Potter", undercover: "Lord of the Rings", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Star Wars", undercover: "Star Trek", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Lightsaber", undercover: "Laser Gun", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Hogwarts", undercover: "Narnia", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Magic Wand", undercover: "Wizard Staff", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Jedi", undercover: "Sith", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Darth Vader", undercover: "Kylo Ren", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Voldemort", undercover: "Sauron", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Hermione Granger", undercover: "Ron Weasley", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Optimus Prime", undercover: "Bumblebee", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Transformers", undercover: "Gundam", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Avatar (Pandora)", undercover: "Guardians of the Galaxy", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Yoda", undercover: "Baby Yoda (Grogu)", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Time Travel", undercover: "Teleportation", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Invisibility Cloak", undercover: "Disguise", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Alien (Xenomorph)", undercover: "Predator", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "The Matrix", undercover: "Inception", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Millennium Falcon", undercover: "Death Star", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Dumbledore", undercover: "Gandalf", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Flying Broomstick", undercover: "Magic Carpet", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Robot", undercover: "Cyborg", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Quidditch", undercover: "Podracing", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Elf", undercover: "Hobbit", category: "Sci-Fi & Fantasy", difficulty: "medium" },
  { civilian: "Spaceship", undercover: "Flying Saucer", category: "Sci-Fi & Fantasy", difficulty: "hard" },
  { civilian: "Jurassic Park", undercover: "Godzilla", category: "Sci-Fi & Fantasy", difficulty: "medium" },

  // Vehicles
  { civilian: "Car", undercover: "Van", category: "Vehicles", difficulty: "hard" },
  { civilian: "Motorcycle", undercover: "Scooter", category: "Vehicles", difficulty: "hard" },
  { civilian: "Grab Car", undercover: "Taxi", category: "Vehicles", difficulty: "hard" },
  { civilian: "Bus", undercover: "Tour Coach", category: "Vehicles", difficulty: "hard" },
  { civilian: "LRT", undercover: "MRT", category: "Vehicles", difficulty: "hard" },
  { civilian: "Monorail", undercover: "Train", category: "Vehicles", difficulty: "hard" },
  { civilian: "Bicycle", undercover: "Mountain Bike", category: "Vehicles", difficulty: "hard" },
  { civilian: "Lorry", undercover: "Pickup Truck", category: "Vehicles", difficulty: "hard" },
  { civilian: "Ferry", undercover: "Cruise Ship", category: "Vehicles", difficulty: "medium" },
  { civilian: "Helicopter", undercover: "Aeroplane", category: "Vehicles", difficulty: "medium" },
  { civilian: "Ambulance", undercover: "Police Car", category: "Vehicles", difficulty: "hard" },
  { civilian: "Fire Engine", undercover: "Tow Truck", category: "Vehicles", difficulty: "medium" },
  { civilian: "Jet Ski", undercover: "Speedboat", category: "Vehicles", difficulty: "hard" },
  { civilian: "Supercar", undercover: "Sports Car", category: "Vehicles", difficulty: "hard" },
  { civilian: "Honda", undercover: "Toyota", category: "Vehicles", difficulty: "hard" },
  { civilian: "Perodua Myvi", undercover: "Perodua Axia", category: "Vehicles", difficulty: "hard" },
  { civilian: "Electric Car (EV)", undercover: "Hybrid Car", category: "Vehicles", difficulty: "hard" },
  { civilian: "Skateboard", undercover: "Rollerblade", category: "Vehicles", difficulty: "hard" },
  { civilian: "Submarine", undercover: "Ship", category: "Vehicles", difficulty: "medium" },
  { civilian: "Tractor", undercover: "Bulldozer", category: "Vehicles", difficulty: "hard" },
  { civilian: "Sedan", undercover: "SUV", category: "Vehicles", difficulty: "hard" },
  { civilian: "Aeroplane", undercover: "Private Jet", category: "Vehicles", difficulty: "hard" },
  { civilian: "Tricycle", undercover: "Bicycle", category: "Vehicles", difficulty: "hard" },
  { civilian: "Luxury Yacht", undercover: "Fishing Boat", category: "Vehicles", difficulty: "medium" },
  { civilian: "Food Truck", undercover: "Delivery Van", category: "Vehicles", difficulty: "hard" },

  // Musical Instruments
  { civilian: "Acoustic Guitar", undercover: "Electric Guitar", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Guitar", undercover: "Ukulele", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Piano", undercover: "Keyboard", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Drum Kit", undercover: "Tambourine", category: "Musical Instruments", difficulty: "medium" },
  { civilian: "Flute", undercover: "Recorder", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Violin", undercover: "Cello", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Trumpet", undercover: "Trombone", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Harmonica", undercover: "Melodica", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Microphone", undercover: "Megaphone", category: "Musical Instruments", difficulty: "medium" },
  { civilian: "Cymbal", undercover: "Gong", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Bass Guitar", undercover: "Lead Guitar", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Triangle", undercover: "Handbell", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Grand Piano", undercover: "Upright Piano", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Harp", undercover: "Lyre", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Whistle", undercover: "Flute", category: "Musical Instruments", difficulty: "medium" },
  { civilian: "Drumstick", undercover: "Conductor Baton", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Saxophone", undercover: "Clarinet", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Bongo Drums", undercover: "Conga Drums", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Xylophone", undercover: "Marimba", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Organ", undercover: "Piano", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Accordion", undercover: "Harmonica", category: "Musical Instruments", difficulty: "medium" },
  { civilian: "Snare Drum", undercover: "Bass Drum", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Guitar Pick", undercover: "Guitar Cable", category: "Musical Instruments", difficulty: "medium" },
  { civilian: "Banjo", undercover: "Acoustic Guitar", category: "Musical Instruments", difficulty: "hard" },
  { civilian: "Headphones", undercover: "Earphones", category: "Musical Instruments", difficulty: "hard" },

  // Office
  { civilian: "Laptop", undercover: "Desktop Computer", category: "Office", difficulty: "hard" },
  { civilian: "Computer Mouse", undercover: "Trackpad", category: "Office", difficulty: "hard" },
  { civilian: "Stapler", undercover: "Paperclip", category: "Office", difficulty: "hard" },
  { civilian: "Whiteboard", undercover: "Notice Board", category: "Office", difficulty: "hard" },
  { civilian: "Ballpoint Pen", undercover: "Marker Pen", category: "Office", difficulty: "hard" },
  { civilian: "Printer", undercover: "Photostat Machine", category: "Office", difficulty: "hard" },
  { civilian: "Meeting Room", undercover: "Conference Room", category: "Office", difficulty: "hard" },
  { civilian: "Zoom Call", undercover: "Google Meet", category: "Office", difficulty: "hard" },
  { civilian: "Boss", undercover: "Manager", category: "Office", difficulty: "hard" },
  { civilian: "Full-time", undercover: "Part-time", category: "Office", difficulty: "medium" },
  { civilian: "Overtime (OT)", undercover: "Work From Home (WFH)", category: "Office", difficulty: "medium" },
  { civilian: "Monthly Salary", undercover: "Year-end Bonus", category: "Office", difficulty: "hard" },
  { civilian: "Resignation", undercover: "Termination", category: "Office", difficulty: "hard" },
  { civilian: "Coffee Machine", undercover: "Water Dispenser", category: "Office", difficulty: "hard" },
  { civilian: "Cubicle", undercover: "Work Desk", category: "Office", difficulty: "hard" },
  { civilian: "Microsoft Excel", undercover: "Google Sheets", category: "Office", difficulty: "hard" },
  { civilian: "PowerPoint", undercover: "Slide Presentation", category: "Office", difficulty: "hard" },
  { civilian: "Email", undercover: "Official Memo", category: "Office", difficulty: "hard" },
  { civilian: "Punch Card", undercover: "Fingerprint Scanner", category: "Office", difficulty: "hard" },
  { civilian: "Office Chair", undercover: "Swivel Chair", category: "Office", difficulty: "hard" },
  { civilian: "Paper Shredder", undercover: "Waste Basket", category: "Office", difficulty: "medium" },
  { civilian: "Name Card", undercover: "Staff Access Card", category: "Office", difficulty: "hard" },
  { civilian: "Promotion", undercover: "Salary Raise", category: "Office", difficulty: "hard" },
  { civilian: "Lanyard", undercover: "ID Badge Clip", category: "Office", difficulty: "hard" },
  { civilian: "Wall Calendar", undercover: "Planner Diary", category: "Office", difficulty: "hard" },

  // Programming
  { civilian: "Python", undercover: "Java", category: "Programming", difficulty: "hard" },
  { civilian: "HTML", undercover: "CSS", category: "Programming", difficulty: "hard" },
  { civilian: "Website", undercover: "Mobile App", category: "Programming", difficulty: "medium" },
  { civilian: "Frontend", undercover: "Backend", category: "Programming", difficulty: "hard" },
  { civilian: "Software Bug", undercover: "System Glitch", category: "Programming", difficulty: "hard" },
  { civilian: "Hacker", undercover: "Software Engineer", category: "Programming", difficulty: "medium" },
  { civilian: "Password", undercover: "PIN Code", category: "Programming", difficulty: "hard" },
  { civilian: "Wi-Fi", undercover: "Bluetooth", category: "Programming", difficulty: "hard" },
  { civilian: "iPhone (iOS)", undercover: "Android", category: "Programming", difficulty: "medium" },
  { civilian: "Mac", undercover: "Windows PC", category: "Programming", difficulty: "hard" },
  { civilian: "Google Chrome", undercover: "Apple Safari", category: "Programming", difficulty: "hard" },
  { civilian: "Folder", undercover: "File", category: "Programming", difficulty: "hard" },
  { civilian: "Coding", undercover: "Typing", category: "Programming", difficulty: "medium" },
  { civilian: "RAM", undercover: "Hard Drive (SSD)", category: "Programming", difficulty: "hard" },
  { civilian: "Keyboard", undercover: "Mouse", category: "Programming", difficulty: "medium" },
  { civilian: "Dark Mode", undercover: "Light Mode", category: "Programming", difficulty: "hard" },
  { civilian: "Database", undercover: "Cloud Storage", category: "Programming", difficulty: "medium" },
  { civilian: "Error Code", undercover: "Blue Screen Crash", category: "Programming", difficulty: "hard" },
  { civilian: "Download", undercover: "Upload", category: "Programming", difficulty: "hard" },
  { civilian: "GitHub", undercover: "Git", category: "Programming", difficulty: "hard" },
  { civilian: "Algorithm", undercover: "Source Code", category: "Programming", difficulty: "hard" },
  { civilian: "Software", undercover: "Hardware", category: "Programming", difficulty: "medium" },
  { civilian: "Terminal", undercover: "Command Prompt", category: "Programming", difficulty: "hard" },
  { civilian: "Artificial Intelligence (AI)", undercover: "Robot", category: "Programming", difficulty: "medium" },
  { civilian: "Web Server", undercover: "Cloud Hosting", category: "Programming", difficulty: "hard" },

  // Fashion
  { civilian: "T-Shirt", undercover: "Polo Shirt", category: "Fashion", difficulty: "hard" },
  { civilian: "Jeans", undercover: "Trousers", category: "Fashion", difficulty: "hard" },
  { civilian: "Hoodie", undercover: "Sweatshirt", category: "Fashion", difficulty: "hard" },
  { civilian: "Jacket", undercover: "Overcoat", category: "Fashion", difficulty: "hard" },
  { civilian: "Slippers (Selipar)", undercover: "Sandals", category: "Fashion", difficulty: "hard" },
  { civilian: "Sneakers", undercover: "Running Shoes", category: "Fashion", difficulty: "hard" },
  { civilian: "High Heels", undercover: "Wedges", category: "Fashion", difficulty: "hard" },
  { civilian: "Baseball Cap", undercover: "Bucket Hat", category: "Fashion", difficulty: "hard" },
  { civilian: "Sunglasses", undercover: "Spectacles", category: "Fashion", difficulty: "hard" },
  { civilian: "Backpack", undercover: "Sling Bag", category: "Fashion", difficulty: "hard" },
  { civilian: "Wallet", undercover: "Purse", category: "Fashion", difficulty: "hard" },
  { civilian: "Belt", undercover: "Suspenders", category: "Fashion", difficulty: "medium" },
  { civilian: "Finger Ring", undercover: "Bracelet", category: "Fashion", difficulty: "hard" },
  { civilian: "Necklace", undercover: "Gold Chain", category: "Fashion", difficulty: "hard" },
  { civilian: "Shorts", undercover: "Boxer Shorts", category: "Fashion", difficulty: "hard" },
  { civilian: "Ankle Socks", undercover: "Stockings", category: "Fashion", difficulty: "hard" },
  { civilian: "Scarf", undercover: "Shawl / Tudung", category: "Fashion", difficulty: "hard" },
  { civilian: "Baju Kurung", undercover: "Baju Kebaya", category: "Fashion", difficulty: "hard" },
  { civilian: "Baju Melayu", undercover: "Kurta", category: "Fashion", difficulty: "hard" },
  { civilian: "Tuxedo", undercover: "Business Suit", category: "Fashion", difficulty: "hard" },
  { civilian: "Perfume", undercover: "Body Deodorant", category: "Fashion", difficulty: "hard" },
  { civilian: "Lipstick", undercover: "Lip Balm", category: "Fashion", difficulty: "hard" },
  { civilian: "Wristwatch", undercover: "Smartwatch", category: "Fashion", difficulty: "hard" },
  { civilian: "Leather Boots", undercover: "Ankle Boots", category: "Fashion", difficulty: "hard" },
  { civilian: "Umbrella", undercover: "Raincoat", category: "Fashion", difficulty: "medium" },

  // Landmarks
  { civilian: "KLCC (Twin Towers)", undercover: "KL Tower", category: "Landmarks", difficulty: "hard" },
  { civilian: "Batu Caves", undercover: "Merdeka 118", category: "Landmarks", difficulty: "medium" },
  { civilian: "Penang Bridge", undercover: "Second Penang Bridge", category: "Landmarks", difficulty: "hard" },
  { civilian: "Eiffel Tower", undercover: "Tokyo Tower", category: "Landmarks", difficulty: "hard" },
  { civilian: "Statue of Liberty", undercover: "Singapore Merlion", category: "Landmarks", difficulty: "medium" },
  { civilian: "Big Ben", undercover: "London Eye", category: "Landmarks", difficulty: "hard" },
  { civilian: "Taj Mahal", undercover: "Great Wall of China", category: "Landmarks", difficulty: "medium" },
  { civilian: "Pyramids of Giza", undercover: "Great Sphinx", category: "Landmarks", difficulty: "hard" },
  { civilian: "Burj Khalifa", undercover: "Merdeka 118", category: "Landmarks", difficulty: "hard" },
  { civilian: "Mount Kinabalu", undercover: "Mount Everest", category: "Landmarks", difficulty: "hard" },
  { civilian: "Sydney Opera House", undercover: "Sydney Harbour Bridge", category: "Landmarks", difficulty: "hard" },
  { civilian: "Colosseum", undercover: "Leaning Tower of Pisa", category: "Landmarks", difficulty: "medium" },
  { civilian: "Times Square", undercover: "Hollywood Walk of Fame", category: "Landmarks", difficulty: "medium" },
  { civilian: "Golden Gate Bridge", undercover: "Penang Bridge", category: "Landmarks", difficulty: "medium" },
  { civilian: "Genting Highlands", undercover: "Cameron Highlands", category: "Landmarks", difficulty: "hard" },
  { civilian: "Sunway Lagoon", undercover: "Legoland Malaysia", category: "Landmarks", difficulty: "hard" },
  { civilian: "Dataran Merdeka", undercover: "Putrajaya Mosque", category: "Landmarks", difficulty: "hard" },
  { civilian: "Niagara Falls", undercover: "Victoria Falls", category: "Landmarks", difficulty: "hard" },
  { civilian: "Grand Canyon", undercover: "Mount Everest", category: "Landmarks", difficulty: "medium" },
  { civilian: "Stonehenge", undercover: "Easter Island Statues", category: "Landmarks", difficulty: "hard" },
  { civilian: "Disneyland Castle", undercover: "Universal Studios Globe", category: "Landmarks", difficulty: "hard" },
  { civilian: "The White House", undercover: "The Pentagon", category: "Landmarks", difficulty: "hard" },
  { civilian: "Petra (Jordan)", undercover: "Taj Mahal", category: "Landmarks", difficulty: "medium" },
  { civilian: "Christ the Redeemer", undercover: "Statue of Liberty", category: "Landmarks", difficulty: "hard" },
  { civilian: "National Stadium Bukit Jalil", undercover: "Sepang Circuit", category: "Landmarks", difficulty: "medium" },

  // Furniture & Decor
  { civilian: "Sofa", undercover: "Couch", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Armchair", undercover: "Recliner", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Coffee Table", undercover: "Dining Table", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Wardrobe", undercover: "Built-in Closet", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Bed Frame", undercover: "Mattress", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Pillow", undercover: "Bolster", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Blanket", undercover: "Comforter", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Window Curtain", undercover: "Window Blinds", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Floor Carpet", undercover: "Doormat", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Ceiling Fan", undercover: "Stand Fan", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Air Conditioner", undercover: "Air Cooler", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Mirror", undercover: "Dressing Table", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Bookshelf", undercover: "Display Cabinet", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Table Lamp", undercover: "Night Light", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Wall Clock", undercover: "Alarm Clock", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Dustbin", undercover: "Laundry Basket", category: "Furniture & Decor", difficulty: "medium" },
  { civilian: "Shoe Rack", undercover: "Coat Hanger Rack", category: "Furniture & Decor", difficulty: "medium" },
  { civilian: "Flower Vase", undercover: "Indoor Plant Pot", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Beanbag", undercover: "Throw Cushion", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Wooden Stool", undercover: "Dining Chair", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Chandelier", undercover: "Ceiling Light", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Photo Frame", undercover: "Wall Painting", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Ironing Board", undercover: "Clothes Drying Rack", category: "Furniture & Decor", difficulty: "medium" },
  { civilian: "Floor Mat", undercover: "Bath Mat", category: "Furniture & Decor", difficulty: "hard" },
  { civilian: "Drawer", undercover: "Cupboard", category: "Furniture & Decor", difficulty: "hard" },

  // Tools & Hardware
  { civilian: "Hammer", undercover: "Rubber Mallet", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Screwdriver", undercover: "Test Pen", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Power Drill", undercover: "Impact Wrench", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Wood Screw", undercover: "Iron Nail", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Hex Nut", undercover: "Threaded Bolt", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Pliers", undercover: "Wire Cutter", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Measuring Tape", undercover: "Plastic Ruler", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Duct Tape", undercover: "Masking Tape", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Hand Saw", undercover: "Chainsaw", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Scissors", undercover: "Penknife (Cutter)", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Extension Ladder", undercover: "Step Stool", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Super Glue", undercover: "Hot Glue Gun", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Sandpaper", undercover: "Steel Wire Brush", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Spanner", undercover: "Adjustable Wrench", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Torchlight", undercover: "Headlamp", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Padlock", undercover: "Door Key", category: "Tools & Hardware", difficulty: "medium" },
  { civilian: "Extension Trailing Socket", undercover: "Power Adapter Plug", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Paintbrush", undercover: "Paint Roller", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Wheelbarrow", undercover: "Heavy Trolley", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Cable Tie", undercover: "Rubber Band", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Spirit Level", undercover: "Measuring Tape", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Safety Helmet", undercover: "Safety Goggles", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "WD-40 Spray", undercover: "Lubricant Oil", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Toolbox", undercover: "Tool Belt Bag", category: "Tools & Hardware", difficulty: "hard" },
  { civilian: "Shovel", undercover: "Garden Spade", category: "Tools & Hardware", difficulty: "hard" },

  // Hobbies & Crafts
  { civilian: "Painting", undercover: "Sketching", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Baking", undercover: "Cooking", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Knitting", undercover: "Crocheting", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Photography", undercover: "Videography", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Freshwater Fishing", undercover: "Squid Jigging", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Home Gardening", undercover: "Vegetable Farming", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Reading Novels", undercover: "Reading Comics", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Road Cycling", undercover: "Jogging", category: "Hobbies & Crafts", difficulty: "medium" },
  { civilian: "Camping", undercover: "Glamping", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Board Games", undercover: "Card Games", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Karaoke Singing", undercover: "Choral Singing", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Origami", undercover: "Paper Mache", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Pottery", undercover: "Clay Sculpting", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Calligraphy", undercover: "Hand Lettering", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Diary Journaling", undercover: "Scrapbooking", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Swimming", undercover: "Snorkeling", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Jungle Trekking", undercover: "Mountain Hiking", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Bowling", undercover: "Pool / Snooker", category: "Hobbies & Crafts", difficulty: "medium" },
  { civilian: "Hip-Hop Dance", undercover: "Zumba", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Cosplay", undercover: "Halloween Costume", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Skateboarding", undercover: "Rollerblading", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Jigsaw Puzzle", undercover: "Rubik's Cube", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Flower Arranging", undercover: "Bonsai Trimming", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Sewing", undercover: "Clothes Altering", category: "Hobbies & Crafts", difficulty: "hard" },
  { civilian: "Bird Watching", undercover: "Nature Photography", category: "Hobbies & Crafts", difficulty: "hard" },

  // Football — append-only below this point: pair ids are positional, so new
  // entries must go at the end or saved picks in existing rooms would shift.
  { civilian: "Manchester United", undercover: "Manchester City", category: "Football", difficulty: "medium" },
  { civilian: "Real Madrid", undercover: "Barcelona", category: "Football", difficulty: "medium" },
  { civilian: "Liverpool", undercover: "Everton", category: "Football", difficulty: "hard" },
  { civilian: "Arsenal", undercover: "Tottenham", category: "Football", difficulty: "hard" },
  { civilian: "Chelsea", undercover: "Arsenal", category: "Football", difficulty: "medium" },
  { civilian: "Bayern Munich", undercover: "Borussia Dortmund", category: "Football", difficulty: "hard" },
  { civilian: "Juventus", undercover: "AC Milan", category: "Football", difficulty: "hard" },
  { civilian: "Inter Milan", undercover: "AC Milan", category: "Football", difficulty: "hard" },
  { civilian: "PSG", undercover: "AS Monaco", category: "Football", difficulty: "hard" },
  { civilian: "Ajax", undercover: "PSV Eindhoven", category: "Football", difficulty: "hard" },
  { civilian: "Messi", undercover: "Ronaldo", category: "Football", difficulty: "medium" },
  { civilian: "Neymar", undercover: "Mbappe", category: "Football", difficulty: "hard" },
  { civilian: "Haaland", undercover: "Mbappe", category: "Football", difficulty: "hard" },
  { civilian: "Salah", undercover: "Mane", category: "Football", difficulty: "hard" },
  { civilian: "De Bruyne", undercover: "Bruno Fernandes", category: "Football", difficulty: "hard" },
  { civilian: "Zidane", undercover: "Ronaldinho", category: "Football", difficulty: "hard" },
  { civilian: "Beckham", undercover: "Ryan Giggs", category: "Football", difficulty: "hard" },
  { civilian: "Pele", undercover: "Maradona", category: "Football", difficulty: "hard" },
  { civilian: "Iniesta", undercover: "Xavi", category: "Football", difficulty: "hard" },
  { civilian: "Van Dijk", undercover: "Sergio Ramos", category: "Football", difficulty: "hard" },
  { civilian: "World Cup", undercover: "Euro Cup", category: "Football", difficulty: "medium" },
  { civilian: "Champions League", undercover: "Europa League", category: "Football", difficulty: "hard" },
  { civilian: "Premier League", undercover: "La Liga", category: "Football", difficulty: "hard" },
  { civilian: "Ballon d'Or", undercover: "Golden Boot", category: "Football", difficulty: "hard" },
  { civilian: "Penalty Kick", undercover: "Free Kick", category: "Football", difficulty: "hard" },
  { civilian: "Red Card", undercover: "Yellow Card", category: "Football", difficulty: "hard" },
  { civilian: "Offside", undercover: "Handball", category: "Football", difficulty: "hard" },
  { civilian: "Goalkeeper", undercover: "Defender", category: "Football", difficulty: "medium" },
  { civilian: "Hat-trick", undercover: "Brace", category: "Football", difficulty: "hard" },
  { civilian: "Old Trafford", undercover: "Anfield", category: "Football", difficulty: "hard" },

  // Countries
  { civilian: "Japan", undercover: "South Korea", category: "Countries", difficulty: "medium" },
  { civilian: "Malaysia", undercover: "Indonesia", category: "Countries", difficulty: "hard" },
  { civilian: "Singapore", undercover: "Hong Kong", category: "Countries", difficulty: "hard" },
  { civilian: "Thailand", undercover: "Vietnam", category: "Countries", difficulty: "hard" },
  { civilian: "China", undercover: "India", category: "Countries", difficulty: "medium" },
  { civilian: "United States", undercover: "Canada", category: "Countries", difficulty: "medium" },
  { civilian: "Brazil", undercover: "Argentina", category: "Countries", difficulty: "medium" },
  { civilian: "France", undercover: "Italy", category: "Countries", difficulty: "hard" },
  { civilian: "Spain", undercover: "Portugal", category: "Countries", difficulty: "hard" },
  { civilian: "Germany", undercover: "Austria", category: "Countries", difficulty: "hard" },
  { civilian: "England", undercover: "Scotland", category: "Countries", difficulty: "hard" },
  { civilian: "Netherlands", undercover: "Belgium", category: "Countries", difficulty: "hard" },
  { civilian: "Switzerland", undercover: "Sweden", category: "Countries", difficulty: "hard" },
  { civilian: "Norway", undercover: "Finland", category: "Countries", difficulty: "hard" },
  { civilian: "Russia", undercover: "Ukraine", category: "Countries", difficulty: "hard" },
  { civilian: "Turkey", undercover: "Greece", category: "Countries", difficulty: "hard" },
  { civilian: "Egypt", undercover: "Morocco", category: "Countries", difficulty: "hard" },
  { civilian: "South Africa", undercover: "Nigeria", category: "Countries", difficulty: "hard" },
  { civilian: "Australia", undercover: "New Zealand", category: "Countries", difficulty: "hard" },
  { civilian: "Mexico", undercover: "Colombia", category: "Countries", difficulty: "hard" },
  { civilian: "Saudi Arabia", undercover: "United Arab Emirates", category: "Countries", difficulty: "hard" },
  { civilian: "Pakistan", undercover: "Bangladesh", category: "Countries", difficulty: "hard" },
  { civilian: "Philippines", undercover: "Indonesia", category: "Countries", difficulty: "hard" },
  { civilian: "Brunei", undercover: "Malaysia", category: "Countries", difficulty: "hard" },
  { civilian: "Italy", undercover: "Greece", category: "Countries", difficulty: "medium" },

  // Valorant
  { civilian: "Jett", undercover: "Raze", category: "Valorant", difficulty: "hard" },
  { civilian: "Sage", undercover: "Skye", category: "Valorant", difficulty: "hard" },
  { civilian: "Reyna", undercover: "Phoenix", category: "Valorant", difficulty: "hard" },
  { civilian: "Omen", undercover: "Brimstone", category: "Valorant", difficulty: "hard" },
  { civilian: "Sova", undercover: "Cypher", category: "Valorant", difficulty: "hard" },
  { civilian: "Killjoy", undercover: "Cypher", category: "Valorant", difficulty: "hard" },
  { civilian: "Viper", undercover: "Brimstone", category: "Valorant", difficulty: "hard" },
  { civilian: "Chamber", undercover: "Deadlock", category: "Valorant", difficulty: "hard" },
  { civilian: "Neon", undercover: "Jett", category: "Valorant", difficulty: "hard" },
  { civilian: "Astra", undercover: "Omen", category: "Valorant", difficulty: "hard" },
  { civilian: "KAY/O", undercover: "Breach", category: "Valorant", difficulty: "hard" },
  { civilian: "Fade", undercover: "Sova", category: "Valorant", difficulty: "hard" },
  { civilian: "Harbor", undercover: "Viper", category: "Valorant", difficulty: "hard" },
  { civilian: "Gekko", undercover: "Skye", category: "Valorant", difficulty: "hard" },
  { civilian: "Iso", undercover: "Yoru", category: "Valorant", difficulty: "hard" },
  { civilian: "Clove", undercover: "Astra", category: "Valorant", difficulty: "hard" },
  { civilian: "Vandal", undercover: "Phantom", category: "Valorant", difficulty: "hard" },
  { civilian: "Operator", undercover: "Marshal", category: "Valorant", difficulty: "hard" },
  { civilian: "Sheriff", undercover: "Ghost", category: "Valorant", difficulty: "hard" },
  { civilian: "Spike", undercover: "Defuse Kit", category: "Valorant", difficulty: "medium" },
  { civilian: "Haven", undercover: "Bind", category: "Valorant", difficulty: "hard" },
  { civilian: "Ascent", undercover: "Icebox", category: "Valorant", difficulty: "hard" },
  { civilian: "Split", undercover: "Fracture", category: "Valorant", difficulty: "hard" },
  { civilian: "Radiant", undercover: "Immortal", category: "Valorant", difficulty: "hard" },
  { civilian: "Ace", undercover: "Clutch", category: "Valorant", difficulty: "hard" },
  { civilian: "Headshot", undercover: "Bodyshot", category: "Valorant", difficulty: "hard" },
  { civilian: "Duelist", undercover: "Controller", category: "Valorant", difficulty: "hard" },
  { civilian: "Ultimate", undercover: "Ability", category: "Valorant", difficulty: "hard" },
];

export interface DrawnPair {
  civilian: string;
  undercover: string;
  category: string;
}

// A pair's stable id is its index into WORD_PAIRS (the array order never changes at runtime).
export function wordPairId(index: number): string {
  return String(index);
}

export function listWordPairs(): Array<WordPair & { id: string }> {
  return WORD_PAIRS.map((p, i) => ({ ...p, id: wordPairId(i) }));
}

// Same selection rules as pickWordPair, but over a bank supplied at runtime
// (the admin-editable word bank) rather than the static built-in list.
export function pickFromBank(
  bank: Array<{ id: string; civilian: string; undercover: string; category: string; difficulty: string }>,
  difficulty: "any" | "easy" | "medium" | "hard",
  disabledIds: string[] = [],
  customPairs: Array<{ civilian: string; undercover: string }> = [],
  mode: "all" | "pick" | "custom" = "all"
): DrawnPair {
  const custom: DrawnPair[] = customPairs.map((p) => ({
    civilian: p.civilian,
    undercover: p.undercover,
    category: "Your words",
  }));

  if (mode === "custom" && custom.length > 0) {
    return custom[Math.floor(Math.random() * custom.length)];
  }

  const disabled = new Set(disabledIds);
  const matches = (p: { difficulty: string }) => difficulty === "any" || p.difficulty === difficulty;
  const eligible = bank.filter((p) => matches(p) && (mode === "all" || !disabled.has(p.id)));

  let pool: DrawnPair[] = [...eligible, ...custom];
  if (pool.length === 0) pool = bank.filter(matches);
  if (pool.length === 0) pool = bank.length > 0 ? bank : WORD_PAIRS;
  return pool[Math.floor(Math.random() * pool.length)];
}

// Host-written pairs are always eligible — they were added on purpose, so they
// skip both the difficulty filter and the per-pair toggles.
export function pickWordPair(
  difficulty: "any" | "easy" | "medium" | "hard",
  disabledIds: string[] = [],
  customPairs: Array<{ civilian: string; undercover: string }> = [],
  mode: "all" | "pick" | "custom" = "all"
): DrawnPair {
  const custom: DrawnPair[] = customPairs.map((p) => ({
    civilian: p.civilian,
    undercover: p.undercover,
    category: "Your words",
  }));

  if (mode === "custom" && custom.length > 0) {
    return custom[Math.floor(Math.random() * custom.length)];
  }

  const disabled = new Set(disabledIds);
  const matchesDifficulty = (p: WordPair) => difficulty === "any" || p.difficulty === difficulty;
  const builtin = WORD_PAIRS.filter(
    (p, i) => matchesDifficulty(p) && (mode === "all" || !disabled.has(wordPairId(i)))
  );

  let pool: DrawnPair[] = [...builtin, ...custom];
  if (pool.length === 0) pool = WORD_PAIRS.filter(matchesDifficulty);
  if (pool.length === 0) pool = WORD_PAIRS;
  return pool[Math.floor(Math.random() * pool.length)];
}
